### ISSUE TITLE
Unable to run main_test.py

### ISSUE THREAD

**Issue by fredericgo** [imisra/latent-noise-icnm#1]
After finishing the step of downloading ground truth files, I ran : python main_test.py, but I get the following message. 

Traceback (most recent call last):
  File "main_test.py", line 427, in <module>
    mainTest();
  File "main_test.py", line 254, in mainTest
    imdb = meu.get_imdb(testSetName, testSetSplit);
  File "/data/fredericgo/latent-noise-icnm/./data_model_utils.py", line 50, in get_imdb
    imdb = coco_voc.coco_voc(dataset, splitName, image_path=imdbPaths['imageDir'], captionJsonPath = imdbPaths['jsonPath'])
  File "/data/fredericgo/latent-noise-icnm/./coco_voc.py", line 20, in **init**
    self._coco_caption_data = COCO(captionJsonPath);
  File "/data/fredericgo/latent-noise-icnm/coco/PythonAPI/pycocotools/coco.py", line 73, in __init__
    dataset = json.load(open(annotation_file, 'r'))
IOError: [Errno 2] No such file or directory: './data/coco/annotations/captions_valid22014.json'

**Comment by imisra** [comment]
Hello Frederick,

Thanks for pointing this out!
I have updated the zip file for coco_extra_labels to contain this json file. I also added instructions to the README on where to place the json files.
It should work now.
